---
# Specification of syntax for files used to define a virtual environment
# Format:           YAML 1.1 (See: http://yaml.org/spec/1.1/)
# Author:           Christopher Goes
# Creation Date:    October 12th, 2016
# Current Version:  0.2.0
# Changelog:
#   0.1.0: Created
#   0.2.0: Substantial changes

# Syntax inspirations: 
#   https://docs.docker.com/compose/compose-file/
#   https://docs.ansible.com/ansible/YAMLSyntax.html
# System specification needs to take into account things such as templates, containers
# "Instances" is assumed to be one unless specified otherwise. They cannot be negative or zero.

# *** Labels for syntactic components ***
# Children do not have to be specified if parent is not defined
# If no label is given, then context will determine label (Everything should be labeled eventually)
#
# REQUIRED      These must be defined. Not doing so is an parse-time error.
# Suggested     These should be defined. Will give a warning during parsing.
# Optional      Do not have to be specified
# Option X      One of the options specified at that level must be defined. Not doing so is a parse-time error.

# *** Definitions ***
# vm    Virtual Machine
# ad    Active Directory

# TODO: "enabled" flags to easily toggle sections on and off without having to comment out

# ##################################
# ### Beginning of specification ###

# ** Document Metadata **
metadata:
  name: "a human-readable title for the specification" # REQUIRED
  description: "a human-readable description of specification" # Suggested
  date-created: "date the specification was created" # Suggested. UTC format: YYYY-MM-DD (2016-10-12)
  version: "version of the document" # Optional
  course: "name of the course/class" # Optional
  class: "same as course" # Optional

  # If not defined, default 'infrastructure.yaml' is checked, if not found user is prompted 
  # TODO: define syntax of this file
  infrastructure-config-file: "filename of environment infrastructure info" # Suggested



# ** Groups/Teams **
# User groups, such as teams, students, instructors, etc.
# These are used to apply permissions to the resources and machines in the generated virtual environment.
# Can also be specified as "teams"
# TODO: how do we map users in groups to VMs?
groups:
  Group Regular Example:
    # The three different methods of specifying users for a regular group
    ad-group: "RADICL Users"
    filename: "users.json"
    usernames: [ "user A", "user B" ]

  # For creating batch groups from a common template base, the "template" type can be used
  # Templates use the key letter 'X' to define unique copies of the base
  Group Template Example X: # Note the capital X
    # If instances is specified, the group is assumed to be a template
    instances: 10  # Number of groups created from this template

    # The two differnt methods of specifying users for a template group
    ad-group: "Group X"
    filename: "users-X.json"



# ** Services **
# Definition of services (nodes) that will be created in the enviornment, such as hosts, servers, and routers.
# Case insensitive EXCEPT for resources, such as templates or images
# Template configurations will be overriden if certain options are set
# If containers are used, a GitLab server or Docker registry MUST be specified (TODO: where?)
# Three types of service: template, container, compose
# Template:     Templatized VM in vSphere
# Container:    Docker container
# Compose:      Docker compose file
#
# network-interfaces: List of network interfaces and their optional configurations
# Networks are attached to interfaces in order of their definition, unless explicitly mapped
# TODO: monitoring + management interface configurations
services:
  all-service-types:
    network-interfaces: [] # OPTIONAL [default: template or container specific]  
    os: # Optional
      name: "name of the os"
      version: "version of the os"
      family: "major family os belongs to"
  template-based-service:   # Option A
    template: "name of template in vSphere" # REQUIRED
    template-config: [] # Optional. Configuration of Template settings specified by name. This will override the template's existing settings.
  container-based-service:  # Option B
    image: "name of the docker image"    # REQUIRED
    tag: "tag for the image"             # OPTIONAL [if not specified, "default" is used]
  compose-based-service:    # Option C
    compose-file: "name of compose file" # REQUIRED                                  



# ** Resources **
# Lab resources that are to be utilized. These will be attached to folders, networks, or groups as needed
# Example: access to a specific portion of the power lab. 
# Example: access to RADICL's  Wireless testbed
# TODO: define better
resources:
  resource-p:
    lab: "power-lab"
    resource: "transformer"
  resource-r:
    lab: "radicl"
    resource: "wireless-testbed"

# TODO: monitoring capability specification
#     need ability to specify data sink(s) and annotate nodes as data sources (e.g we put a tap on this network)
# TODO: Default server for saves?
# TODO: Specify network interfaces and hosts that monitoring data will be collected from


# ** Networks **
# Note: distributed vSwitches are an implementation detail of system, and are not considored as part of the specification.
# Non-Private (RFC 1918) networks will result in a warning that can be suppressed.
# VLANs are implicitly defined?
# Don't NEED IP addresses, just named networks. Addresses only matter if running configuration scripts or adding a pre-configured router
# IP version is implicitly defined by address (using ipaddress module in python)
# vSwitches are implicitly defined by networks
# Syntax: subnet-name: "address/mask"
# TODO: monitoring annotations
# TODO: managment/admin networks?
networks: 
  unique-subnets: # Only one of each of these exists. If specified, any hosts will be added to it.
    subnet-name: "192.168.1.0/24" # Address is optional. Subnet is specified using CIDR notation 
  generic-subnets: # Subnets that new instances are created per instance of an exercise
    subnet-name: "192.168.1.0/24"
  base-subnets: # Subnets that will have any values in network portion of address with X are incremented for each instance 
    subnet-name: "192.168.1.0/24"



# ** Folders **
# Assemblages of objects defined previously in file
# TODO: pool distributions
folders:
  folder-a:
    services: # REQUIRED
      service-instance-label: 
        service: service-label # As defined in services
        instances: 2 # OPTONAL [default: 1]
        networks: ["subnet-a", "subnet-b"]
    group: group # REQUIRED (can also be "team")
  folder-b:
    instances: 10 # if instances is specified, this is a template

...