---
metadata:
  name: "PRCCDC 2016 Competition Scenario definition"
  description: "The competition scenario environment that students will use to compete"
  activity: "Pacific Rim Collegiate Cyber Defense Competition"
  prefix: "PRCCDC"
  date-created: "2016-11-01"
  version: "0.5.0"
  infrastructure-config-file: "infra.yaml"
  folder-name: "prccdc-2016"
  root-path: "Competitions/PRCCDC/"
  template-path: "Templates/"

groups:
  Blue Team:
    instances: 10
    filename: "examples/blue-teams.json"
  Red Team:
    ad-group: "Red Team"

services:
  host-type-a:
    template: "PRCCDC Windows 7 Host"
    note: "Default password is Windows1"
    os:
      name: "Windows 7 Enterprise"
      version: "7601"
      family: "Windows/NT"
  host-type-b:
    template: "PRCCDC Windows 10 Host"
    note: "Default password is Windows1"
    os:
      name: "Windows 10 Enterprise"
      version: "10"
      family: "Windows/NT"
  score-bot:
    image: "prccdc/score-bot"
    tag: "0.1.2"
  firewall:
    template: "PRCCDC Firewall"
    note: "Default Username: vyos   Password: vyos"
    template-config:
      video: no
    os:
      name: "VyOS"
      version: "1.1.7"
      family: "Linux/Debian"
  domain-controller:
    template: "PRCCDC Domain Controller"
    note: "Default password is Windows1"
    template-config:
      video: no # RDP is used
    os:
      name: "Windows Server 2012 R2 Datacenter"
      version: "2012 R2"
      distribution: "Datacenter"
      family: "Windows/NT"
  web-server:
    image: "prccdc/apache-server"
    note: "Default password is Password1"
    tag: "2.4.2"
    os:
      name: "Ubuntu 14.04 LTS"
      version: "14.04"
      distribution: "LTS"
      family: "Linux/Debian"
  database-server:
    image: "prccdc/mysql-server"
    note: "Default password is Password1"
    tag: "7"
    os:
      name: "Oracle SunOS 7"
      version: "7"
      family: "Solaris"
  file-server:
    template: "PRCCDC File Server"
    note: "Default password is Windows1"
    template-config:
      video: no
    os:
      name: "Windows Server 2012 R2 Core"
      version: "2012 R2"
      distribution: "Core"
      family: "Windows/NT"
  mail-server:
    template: "PRCCDC Mail Server"
    note: "Default password is Windows1"
    template-config:
      video: no # RDP is used
    os:
      name: "Windows Server 2003"
      version: "2003"
      family: "Windows/NT"
  hvac-server:
    image: "prccdc/hvac-server"
    note: "Default password is Password1"
    tag: "1"
    os:
      name: "FreeBSD"
      family: "BSD"

networks:
  unique-networks:
    competition:
      subnet: "172.30.0.0/16"
      vswitch: "competition_vswitch"
    outside-world: 
      subnet: "172.20.0.0/16"
      vswitch: "competition_vswitch"
    management: 
      subnet: "10.10.10.0/24"
      vswitch: "competition_vswitch"
  generic-networks:
    hosts:
      subnet: "10.0.0.0/24"
      vswitch: "competition_vswitch"
  base-networks:
    services: 
      subnet: "192.168.0.0/24"
      vswitch: "competition_vswitch"

folders:
  external:
    group: 
    description: "The open competition network, where red team and the score bot sit" 
    services:
      edge-router: 
        description: "Connection to outside internet"
        service: firewall
        networks: ["outside-world", "competition", "management"]
      competition-dc: 
        description: "Provides DNS and DHCP"
        service: domain-controller
        networks: ["competition", "management"]
      # Scorebots communicate over a back-end network to randomly select which team gets pinged from which scorebot
      score-bot:  
        description: "Used to score teams"
        service: score-bot
        networks: ["competition", "management"]
        instances: 10
  blue-team:
    instances:
      number: 14
      prefix: "Blue Team "
    group: "Blue Team"
    services:
      # team-member-host:
        # description: "Hosts the blue team members use to access their services"
        # instances: 8 # Number of users on blue team
        # service-pool: [host-type-a, host-type-b]
        # pool-distributions: [0.3, 0.7] # Must add up to 1
        # networks: [hosts] 
      gateway:
        description: "Gateway connecting Blue team networks to the larger competition network"
        service: firewall
        networks: ["competition", "hosts", "services"]
      dc: 
        description: "Domain Controller for Blue Team network. Runs DNS, DHCP, and Active Directory."
        service: domain-controller
        networks: ["services"]
      web:
        description: "Web server hosting the team's page"
        service: web-server
        networks: ["services"]
        scoring:
          ports: [80, 443]
          protocols: ["http", "https"]
          criteria: "criteria-file.yaml"
      db:
        description: "Database"
        service: database-server
        networks: ["services"]
      mail:
        description: "Mail Server"
        service: mail-server
        networks: ["services"]
        scoring:
          ports: [25]
          protocols: ["smtp"]
          criteria: "criteria-file.yaml"
      hvac:
        description: "HVAC Server"
        service: hvac-server
        networks: ["services"]
        scoring:
          ports: [22]
          protocols: ["ssh"]
          criteria: "criteria-file.yaml"
      file:
        description: "File Server"
        service: file-server
        networks: ["services"]
        scoring:
          ports: [21, 445]
          protocols: ["sftp", "smb"]
          criteria: "criteria-file.yaml"
  red-team:
    group: "Red Team"
    services:
      windows-hosts:
        description: "Hosts used by Red Team to attack blue teams"
        service: host-type-b
        networks: ["competition"]
      collaboration-server:
        description: "Server for Red Team collaboration, including Armitage, SFTP, and IRC"
        service: web-server
        networks: ["competition"]
...